#!/usr/bin/python
import argparse
import sys
from compphysutils.parser.parser import parseDatasetConfig

ap = argparse.ArgumentParser(description="Runs only the parseDatasetConfig function on a given filenames, can be used mostly for parsing from a single file format to other.")
ap.add_argument("filenames", metavar="filename", nargs="+", help="Names of the dataset config files.")

args = ap.parse_args()

for filename in args.filenames:
    parseDatasetConfig(filename)

sys.exit(0)
